[package]
name = "rlog"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
regex = "1.11.1"
serde = "1.0.218"
serde_derive = "1.0.218"
toml = "0.8.20"
tui = "0.19.0"
serde_json = "1.0.140"
